package pruebas.PruebasEstructurasLineales;

import entradasalida.SalidaPorDefecto;
import estructuraslineales.ListaDinamica;
import estructuraslineales.ListaDinamicaClave;
import estructuraslineales.ListaEstatica;
import estructurasnolineales.Matriz2;

public class PruebaListaDinamicaClave {
    public static void main(String[] args) {
        ListaDinamicaClave lista = new ListaDinamicaClave();
        SalidaPorDefecto.consola("Prueba agregar elemento a la lista (clave:1, valor: A): " + lista.agregar(1, "A") + "\n");
        SalidaPorDefecto.consola("Prueba agregar elemento a la lista (clave:2, valor: B): " + lista.agregar(2, "B") + "\n");
        SalidaPorDefecto.consola("Prueba agregar elemento a la lista (clave:1, valor: C): " + lista.agregar(1, "C") + "\n");
        SalidaPorDefecto.consola("Prueba agregar elemento a la lista (clave:3, valor: D): " + lista.agregar(3, "D") + "\n");
        SalidaPorDefecto.consola("Prueba agregar elemento a la lista (clave:4, valor: E): " + lista.agregar(4, "E") + "\n");
        SalidaPorDefecto.consola("Prueba agregar elemento a la lista (clave:5, valor: F): " + lista.agregar(5, "F") + "\n");
        lista.imprimir();

        SalidaPorDefecto.consola("Eliminar por clave elemento clave 2: " + lista.eliminar(2) + "\n");
        lista.imprimir();
        SalidaPorDefecto.consola("Eliminar por valor elemento A: " + lista.eliminarContenido("A") + "\n");
        lista.imprimir();
        SalidaPorDefecto.consola("Buscar elemento por su clave (clave 4): " + lista.buscar(4) + "\n");
        lista.imprimir();
        SalidaPorDefecto.consola("Buscar elemento por su contenido (F): " + lista.buscarContenido("F") + "\n");
        lista.imprimir();
        SalidaPorDefecto.consola("Cambiando valor de un elemento por su clave (clave 3) nuevo valor H: " + lista.cambiar(3, "H") + "\n");
        lista.imprimir();
        SalidaPorDefecto.consola("Cambiando valor de un elemento por contenido (F) por S: " + lista.cambiarValor("F", "S") + "\n");
        lista.imprimir();
        SalidaPorDefecto.consola("Imprimir claves: \n");
        lista.imprimirClaves();
        SalidaPorDefecto.consola("Imprimir contenidos: \n");
        lista.imprimirContenidos();
        SalidaPorDefecto.consola("Obteniendo elemento con clave 5: " + lista.obtener(5) + "\n");
        SalidaPorDefecto.consola("Obteniendo numero de elementos en la lista: " + lista.numeroElementos() + "\n");
        SalidaPorDefecto.consola("Prueba vaciar la lista: \n");
        lista.vaciar();
        lista.imprimir();
        SalidaPorDefecto.consola("Rellenando la lista nuevamente:\n");
        SalidaPorDefecto.consola("Prueba agregar elemento a la lista (clave:1, valor: A): " + lista.agregar(1, "A") + "\n");
        SalidaPorDefecto.consola("Prueba agregar elemento a la lista (clave:2, valor: B): " + lista.agregar(2, "B") + "\n");
        SalidaPorDefecto.consola("Prueba agregar elemento a la lista (clave:3, valor: D): " + lista.agregar(3, "D") + "\n");
        SalidaPorDefecto.consola("Prueba agregar elemento a la lista (clave:4, valor: E): " + lista.agregar(4, "E") + "\n");
        SalidaPorDefecto.consola("Prueba agregar elemento a la lista (clave:5, valor: F): " + lista.agregar(5, "F") + "\n");
        lista.imprimir();
        SalidaPorDefecto.consola("Prueba convertir a listas estaticas: \n");
        ListaEstatica listasEstaticas = lista.aListasEstaticas();
        SalidaPorDefecto.consola("Claves:\n");
        ListaEstatica leClaves = (ListaEstatica) listasEstaticas.obtener(0);
        ListaEstatica leContenidos = (ListaEstatica) listasEstaticas.obtener(1);
        leClaves.imprimir();
        SalidaPorDefecto.consola("Contenidos:\n");
        leContenidos.imprimir();
        ListaDinamica listasDinamicas = lista.aListasDinamicas();
        ListaDinamica ldClaves = (ListaDinamica) listasDinamicas.obtener(0);
        ListaDinamica ldContenidos = (ListaDinamica) listasDinamicas.obtener(1);
        SalidaPorDefecto.consola("Prueba convertir a listas dinamicas: \n");
        SalidaPorDefecto.consola("Claves:\n");
        ldClaves.imprimir();
        SalidaPorDefecto.consola("Contenidos:\n");
        ldContenidos.imprimir();
        SalidaPorDefecto.consola("Convertir la lista a matriz2: \n");
        Matriz2 matriz = lista.aMatriz2();
        matriz.imprimirXRenglones();
        ListaDinamicaClave listaagregar = new ListaDinamicaClave();
        listaagregar.agregar(6, "W");
        listaagregar.agregar(7, "X");
        listaagregar.agregar(8, "Z");
        ListaDinamicaClave listaagregar2 = new ListaDinamicaClave();
        listaagregar2.agregar(6, "C");
        listaagregar2.agregar(7, "P");
        listaagregar2.agregar(8, "M");
        SalidaPorDefecto.consola("Agregando lista con claves inexistentes: \n");
        SalidaPorDefecto.consola("Lista a agregar: \n");
        listaagregar.imprimir();
        SalidaPorDefecto.consola("Agregando la lista: " + lista.agregarLista(listaagregar) + "\n");
        lista.imprimir();
        SalidaPorDefecto.consola("Agregando lista con claves existentes: \n");
        SalidaPorDefecto.consola("Lista a agregar: \n");
        listaagregar2.imprimir();
        SalidaPorDefecto.consola("Agregando la lista: " + lista.agregarLista(listaagregar2) + "\n");
        lista.imprimir();
        ListaEstatica clavesNuevas = new ListaEstatica(2);
        clavesNuevas.agregar(9);
        clavesNuevas.agregar(10);
        ListaEstatica contNuevos = new ListaEstatica(2);
        contNuevos.agregar("J");
        contNuevos.agregar("K");
        SalidaPorDefecto.consola("Listas estaticas a agregar: \n");
        SalidaPorDefecto.consola("Claves:\n");
        clavesNuevas.imprimir();
        SalidaPorDefecto.consola("Contenidos:\n");
        contNuevos.imprimir();
        SalidaPorDefecto.consola("Agregando las listas estaticas: " + lista.agregarListasEstaticas(clavesNuevas, contNuevos) + "\n");
        lista.imprimir();
        SalidaPorDefecto.consola("Eliminando valores con clave 5,6,7,8,9, y 10 (para realizar pruebas de agregar listas y matrices):\n");
        lista.eliminar(5);
        lista.eliminar(6);
        lista.eliminar(7);
        lista.eliminar(8);
        lista.eliminar(9);
        lista.eliminar(10);
        lista.imprimir();
        SalidaPorDefecto.consola("Listas dinamicas a agregar:\n");
        ListaDinamica clavesNuevasD = new ListaDinamica();
        ListaDinamica contenidosNuevos= new ListaDinamica();
        clavesNuevasD.agregar(8);
        clavesNuevasD.agregar(10);
        contenidosNuevos.agregar("M");
        contenidosNuevos.agregar("N");
        SalidaPorDefecto.consola("Claves:\n");
        clavesNuevasD.imprimir();
        SalidaPorDefecto.consola("Contenidos:\n");
        contenidosNuevos.imprimir();
        SalidaPorDefecto.consola("Agregando las listas dinamicas: "+ lista.agregarListasDinamicas(clavesNuevasD,contenidosNuevos)+"\n");
        lista.imprimir();
        Matriz2 matrizAgregar = new Matriz2(2,2);
        matrizAgregar.cambiar(0,0,7);
        matrizAgregar.cambiar(1,0,11);
        matrizAgregar.cambiar(0,1,"L");
        matrizAgregar.cambiar(1,1,"Ñ");
        SalidaPorDefecto.consola("Matriz a agregar: \n");
        matrizAgregar.imprimirXRenglones();
        SalidaPorDefecto.consola("Agregando matriz a la lista: " + lista.agregarMatriz2(matrizAgregar) + "\n");
        lista.imprimir();
    }
}
